// Generated by CoffeeScript 1.3.2
(function() {
  var app, express;

  express = require('express');

  app = module.exports = express.createServer();

  require('./config')(app);

  require('./routes')(app);

  app.listen(3000);

}).call(this);
